### ISSUE TITLE
Make entities translatable

### ISSUE THREAD

**Issue by triszt4n** [ftsrg/ftsrg.github.io#12]
But don't use unnecessary gatsby plugin, rather a react hook (useState with boolean).

**Edit**: Right now many of the entities are markdown based, but we should consider changing those to yaml as well?

**Edit 2.0**: Everything uses yaml, so we can just change every field like this:
```yaml
- title:
    en: Title
    hu: Cím
  desc:
    en: Description
    hu: Leírás
  url: asd.com
```

**Edit 3.0:** The idea above needs extra rework. Easier solution: change yamls to have the translation keys instead of the concrete text

Extras:
* http://www.nefmi.gov.hu/felsooktatas/dokumentumok/felsooktatasban-gyakran
*
